version: '3'

services:
  api:
    env_file:
      "./api/.env"
    build:
      context: ./api
      dockerfile: ./Dockerfile
    image: "purfect-creations-api"
    ports:
      - "8000:8000"
  webapp:
    build:
      context: ./webapp
      dockerfile: ./Dockerfile
    image: "purfect-creations-webapp"
    ports:
      - "3000:3000"
    links:
      - "api"